### ISSUE TITLE
Implement a generic getter for IdlValue

### ISSUE THREAD

**Issue by neithanmo** [Zondax/icp-client-cpp#20]
This feature would be useful for interacting with IdlValues, a proposed signature for such method would be:
```
  template <typename T>
  std::optional<T> get();
```
with specialization for each type, for example the current getter for uint8_t values is:
`  bool getInt8(int8_t *val);`
which is not idiomatic, using the template get and a proper specialization, an implementation looks like this:
```
template<>
std::optional<uint8_t> get() {....}
```
which is more idiomatic than the previous version

:link: [zboto Link](https://app.clickup.com/t/861n00ckz)

**Comment by becominginsane** [comment]
Closed by #24
