### ISSUE TITLE
The Service type should be define separately 

### ISSUE THREAD

**Issue by neithanmo** [Zondax/icp-client-cpp#21]
Currently, a Service is a principal,  but in order to generalize over getters and constructors, 
it would be handy if it is defined  in its own class, a simple solution would be:

`class Service: Principal {
     ...
}`

The service is used interchangeably as a Principal. 
these characteristics appeal to an inheritance approach from the Principal class.

:link: [zboto Link](https://app.clickup.com/t/861n00h3y)

**Comment by neithanmo** [comment]
@chcmedeiros any advice here, is there a structural difference from a Service and a Principal? any invariant we can base on to define a concrete class for principals?

**Comment by chcmedeiros** [comment]
From the candid point of view the Principal variant represents a principal value, which is used to identify canisters. A principal is a unique identifier assigned to a canister and is often used for authorization and access control purposes.

On the other hand, the Service variant represents a service type value. A service type used to represent the interface of a canister. As we see on the .did files it defines the methods that can be called on the canister and the types of arguments and return values for those methods. 

In the end the Service variant is used only to indicate that a value is of a service type. 
So I would say 
`class Service: Principal { ... }`
Seems to be a good idea

**Comment by becominginsane** [comment]
It also seems to be how this is represented by candid https://docs.rs/candid/latest/candid/parser/value/enum.IDLValue.html#variant.Service

**Comment by neithanmo** [comment]
Using inheritance is quite complex in this scenario, to ensure the Service is never constructed by its own methods but using the parent class interface, it is necessary to make base class constructors/destructors private plus minor details in deriving class definition. this might be in conflict with how the Principal base class is currently used in the code, in order to continue with this approach we would need to do something like:

- define a PrincipalBase class that would have the same constructors/destructor and members as defined by the current Principal class.
- define a `class Principal : protected PrincipalBase{}`
- define` class Service: protected PrincipalBase{}`

Even with this approach, there are corner cases.
So it is better to follow **Rust** approach and define Service class as a simple wrapper, which will also be move-only.

**Comment by neithanmo** [comment]
fixed via #24
