### ISSUE TITLE
The Number variant for IDLValues should be a concrete type

### ISSUE THREAD

**Issue by neithanmo** [Zondax/icp-client-cpp#22]
Right now the constructor  for IdlValues holding a Number variant is defined as follows:
`IdlValue FromNumber(std::string number);`
and the getter:
`std::string getNumber();`
The Number variant should have a concrete type, to improve ergonomic and generic implementation.

:link: [zboto Link](https://app.clickup.com/t/861n00h9a)

**Comment by chcmedeiros** [comment]
Can we define a structure, similar to record that wraps a string inside.

**Comment by neithanmo** [comment]
fixed via #24
