### ISSUE TITLE
Clarify ownership rules for `IDLValue*` 

### ISSUE THREAD

**Issue by becominginsane** [Zondax/icp-client-cpp#25]
Currently some of the functions take ownership, some don't, and it's in general tricky to enforce them.

Solutions proposed:
* wrap `IDLValue *` into a custom smart pointer
* warp `IDLValue *` with `std::unique_ptr`

:link: [zboto Link](https://app.clickup.com/t/861n06a25)

**Comment by neithanmo** [comment]
As discussed by the team, using `unique_ptr` is the right solution

**Comment by neithanmo** [comment]
closed via #26
