### ISSUE TITLE
Undefined Symbol when building IC example

### ISSUE THREAD

**Issue by chcmedeiros** [Zondax/icp-client-cpp#29]
Undefined symbols for architecture arm64:
  "zondax::IdlValue::IdlValue<IDLValue const*>(IDLValue const*)", referenced from:
      zondax::IdlArgs::getVec() in libagent_cpp.a(idl_args.cpp.o)
      void std::__1::allocator<zondax::IdlValue>::construct[abi:v15006]<zondax::IdlValue, IDLValue const*&>(zondax::IdlValue*, IDLValue const*&) in libagent_cpp.a(idl_value.cpp.o)

:link: [zboto Link](https://app.clickup.com/t/861n0b15v)

**Comment by neithanmo** [comment]
via #30
